// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// WhoamiResponse is returned by Whoami on success.
type WhoamiResponse struct {
	User *WhoamiUser `json:"user"`
}

// GetUser returns WhoamiResponse.User, and is useful for accessing the field via an interface.
func (v *WhoamiResponse) GetUser() *WhoamiUser { return v.User }

// WhoamiUser includes the requested fields of the GraphQL type User.
type WhoamiUser struct {
	User_id          *string  `json:"user_id"`
	Email            *string  `json:"email"`
	Name             *string  `json:"name"`
	Is_admin         *bool    `json:"is_admin"`
	Num_transcripts  *float64 `json:"num_transcripts"`
	Minutes_consumed *float64 `json:"minutes_consumed"`
}

// GetUser_id returns WhoamiUser.User_id, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetUser_id() *string { return v.User_id }

// GetEmail returns WhoamiUser.Email, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetEmail() *string { return v.Email }

// GetName returns WhoamiUser.Name, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetName() *string { return v.Name }

// GetIs_admin returns WhoamiUser.Is_admin, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetIs_admin() *bool { return v.Is_admin }

// GetNum_transcripts returns WhoamiUser.Num_transcripts, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetNum_transcripts() *float64 { return v.Num_transcripts }

// GetMinutes_consumed returns WhoamiUser.Minutes_consumed, and is useful for accessing the field via an interface.
func (v *WhoamiUser) GetMinutes_consumed() *float64 { return v.Minutes_consumed }

// The query executed by Whoami.
const Whoami_Operation = `
query Whoami {
	user {
		user_id
		email
		name
		is_admin
		num_transcripts
		minutes_consumed
	}
}
`

func Whoami(
	ctx_ context.Context,
	client_ graphql.Client,
) (data_ *WhoamiResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "Whoami",
		Query:  Whoami_Operation,
	}

	data_ = &WhoamiResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
