// Package dynamic builds GraphQL query documents with runtime-selected
// selection sets. Used for the three fat-payload ops where client-side
// field projection is insufficient:
//   - meetings list   (transcripts)
//   - meetings get    (transcript)
//   - transcript text (transcript.sentences)
//
// Every other command uses the fixed queries generated by genqlient.
package dynamic

import (
	"fmt"
	"sort"
	"strings"
)

// TranscriptField names the allowed selection keys for the Transcript type.
// Adding a key here makes it available via the `--fields` flag on
// `meetings list`, `meetings get`, and `transcript text`.
type TranscriptField string

const (
	FID              TranscriptField = "id"
	FTitle           TranscriptField = "title"
	FOrganizerEmail  TranscriptField = "organizer_email"
	FHostEmail       TranscriptField = "host_email"
	FMeetingLink     TranscriptField = "meeting_link"
	FDuration        TranscriptField = "duration"
	FDate            TranscriptField = "date"
	FParticipants    TranscriptField = "participants"
	FSummary         TranscriptField = "summary"
	FAnalytics       TranscriptField = "analytics"
	FSentences       TranscriptField = "sentences"
	FTranscriptURL   TranscriptField = "transcript_url"
	FAudioURL        TranscriptField = "audio_url"
	FVideoURL        TranscriptField = "video_url"
	FCalendarID      TranscriptField = "calendar_id"
	FDateString      TranscriptField = "dateString"
	FSpeakers        TranscriptField = "speakers"
	FPrivacy         TranscriptField = "privacy"
	FChannels        TranscriptField = "channels"
)

// subSelections maps a field to its required sub-selection set.
// Leaf scalars have an empty slice.
var subSelections = map[TranscriptField][]string{
	FID:             nil,
	FTitle:          nil,
	FOrganizerEmail: nil,
	FHostEmail:      nil,
	FMeetingLink:    nil,
	FDuration:       nil,
	FDate:           nil,
	FTranscriptURL:  nil,
	FAudioURL:       nil,
	FVideoURL:       nil,
	FCalendarID:     nil,
	FDateString:     nil,
	FPrivacy:        nil,
	FParticipants: {"name", "email"},
	FSpeakers:     {"id", "name"},
	FChannels:     {"id", "title"},
	FSummary:      {"keywords", "action_items", "outline", "overview", "short_summary", "bullet_gist", "gist", "meeting_type", "topics_discussed"},
	FAnalytics:    {"sentiments { negative_pct neutral_pct positive_pct }", "categories { questions date_times tasks metrics }", "speakers { name duration word_count longest_monologue monologues_count filler_words questions duration_pct words_per_minute }"},
	FSentences:    {"index", "speaker_name", "speaker_id", "text", "raw_text", "start_time", "end_time"},
}

// AllFields returns the full set of supported selection keys, sorted.
func AllFields() []string {
	out := make([]string, 0, len(subSelections))
	for k := range subSelections {
		out = append(out, string(k))
	}
	sort.Strings(out)
	return out
}

// DefaultPreview is the selection set used when --transcript=preview.
func DefaultPreview() []TranscriptField {
	return []TranscriptField{FID, FTitle, FDate, FDuration, FOrganizerEmail, FParticipants}
}

// DefaultNone is the minimal selection set used when --transcript=none.
func DefaultNone() []TranscriptField {
	return []TranscriptField{FID, FTitle, FDate, FDuration}
}

// DefaultFull is the full-depth selection including sentences + summary + analytics.
func DefaultFull() []TranscriptField {
	return []TranscriptField{
		FID, FTitle, FDate, FDuration, FOrganizerEmail, FHostEmail, FMeetingLink,
		FParticipants, FSpeakers, FPrivacy, FChannels,
		FSummary, FAnalytics, FSentences, FTranscriptURL, FAudioURL, FVideoURL,
	}
}

// ValidateFields returns an error if any requested key is unknown.
func ValidateFields(fields []string) error {
	for _, f := range fields {
		if _, ok := subSelections[TranscriptField(f)]; !ok {
			return fmt.Errorf("unknown transcript field %q (use --fields ? to list)", f)
		}
	}
	return nil
}

// ParseFields turns a comma-separated --fields value into a slice, trimming space.
func ParseFields(s string) []string {
	out := []string{}
	for _, f := range strings.Split(s, ",") {
		if f = strings.TrimSpace(f); f != "" {
			out = append(out, f)
		}
	}
	return out
}

// BuildTranscriptSelectionSet returns the GraphQL selection set text
// (without surrounding braces) for the requested fields.
func BuildTranscriptSelectionSet(fields []TranscriptField) string {
	if len(fields) == 0 {
		fields = DefaultPreview()
	}
	seen := map[TranscriptField]bool{}
	parts := []string{}
	for _, f := range fields {
		if seen[f] {
			continue
		}
		seen[f] = true
		sub, ok := subSelections[f]
		if !ok {
			continue
		}
		if len(sub) == 0 {
			parts = append(parts, string(f))
		} else {
			parts = append(parts, fmt.Sprintf("%s { %s }", f, strings.Join(sub, " ")))
		}
	}
	return strings.Join(parts, "\n  ")
}

// BuildSingleTranscriptQuery returns a full GraphQL document for the
// `transcript(id:)` query with the requested selection set.
func BuildSingleTranscriptQuery(fields []TranscriptField) string {
	return fmt.Sprintf(`query DynamicTranscript($id: String!) {
  transcript(id: $id) {
    %s
  }
}`, BuildTranscriptSelectionSet(fields))
}

// BuildTranscriptsListQuery returns a full GraphQL document for the
// `transcripts(...)` list query with the requested selection set.
func BuildTranscriptsListQuery(fields []TranscriptField) string {
	return fmt.Sprintf(`query DynamicTranscripts($limit: Int, $skip: Int, $fromDate: DateTime, $toDate: DateTime, $keyword: String, $organizers: [String!], $participants: [String!], $channel_id: String, $mine: Boolean) {
  transcripts(limit: $limit, skip: $skip, fromDate: $fromDate, toDate: $toDate, keyword: $keyword, organizers: $organizers, participants: $participants, channel_id: $channel_id, mine: $mine) {
    %s
  }
}`, BuildTranscriptSelectionSet(fields))
}

// FieldsFromStrings converts a []string to []TranscriptField, preserving order.
func FieldsFromStrings(ss []string) []TranscriptField {
	out := make([]TranscriptField, len(ss))
	for i, s := range ss {
		out[i] = TranscriptField(s)
	}
	return out
}
